version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
















#version: 2
#jobs:
#  test:
#    working_directory: ~/code
#    docker:
#      - image: circleci/android:api-27-alpha
#    environment:
#      JVM_OPTS: -Xmx4608M
#      _JAVA_OPTIONS: "-Xmx4608M -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
#    steps:
#      - checkout
#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
##      - run:
##         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
##         command: sudo chmod +x ./gradlew
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run unit tests
#          command: ./gradlew test
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#      - store_test_results:
#          path: app/build/test-results
#      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
#
#
#  # The deployment task makes use of Gradle scripts.
#  # Both flavors are built in there and uploaded as well.
#  hockeyUpload:
#    working_directory: ~/code
#    resource_class: large
#    docker:
#      - image: circleci/android:api-27-alpha
#    environment:
#      JVM_OPTS: -Xmx4608M
#      _JAVA_OPTIONS: "-Xmx4608M -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
#    steps:
#      - add_ssh_keys:
#          fingerprints:
#            - "b8:13:b3:39:9c:f2:03:17:4f:c0:70:68:76:95:4f:d3"
#      - checkout
#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Increment build version
#          command: ./gradlew autoincrementVersion
#      - run:
#          name: Commit bumped version
#          command: |
#            git config credential.helper 'cache --timeout=120'
#            git config user.email "circle-ci@github.com"
#            git config user.name "Home 24 Deployment Bot"
#            git add version.properties
#            git commit -m "[skip ci] App version bump"
#            # Push quietly to prevent showing the token in log
#            git push -q git@github.com:Home24/MobileApp-Android.git development
#      - run:
#          name: Trigger Hockey upload and proguard mapping as well
#          command: ./gradlew clean hockeyPublish --stacktrace --no-daemon
#
#
## The purpose of the workflow below is to deploy a new build once the `development` branch is updated.
#workflows:
#  version: 2
#  development-cd:
#    jobs:
#      - hockeyUpload:
#          filters:
#            branches:
#              only: development # on this branch only
#
